# Generated by Django 4.2.25 on 2025-10-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('signal_quality', models.IntegerField()),
                ('attention', models.IntegerField()),
                ('meditation', models.IntegerField()),
                ('delta', models.IntegerField()),
                ('theta', models.IntegerField()),
                ('low_alpha', models.IntegerField()),
                ('low_gamma', models.IntegerField()),
                ('low_beta', models.IntegerField()),
                ('high_alpha', models.IntegerField()),
                ('high_gamma', models.IntegerField()),
                ('high_beta', models.IntegerField()),
            ],
        ),
    ]
