<<<<<<< HEAD
# Generated by Django 4.2.25 on 2025-11-01 09:51
=======
# Generated by Django 4.2.25 on 2025-10-29 14:31
>>>>>>> c1ca8f851998afb1bf30cc888e6f7d683215f106

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
<<<<<<< HEAD
                ('name', models.CharField(default='EEG_Data', max_length=255)),
                ('signal_quality', models.IntegerField(default=0)),
                ('attention', models.IntegerField(default=0)),
                ('meditation', models.IntegerField(default=0)),
                ('delta', models.FloatField()),
                ('theta', models.FloatField()),
                ('low_alpha', models.FloatField(default=0)),
                ('low_gamma', models.FloatField(default=0)),
                ('low_beta', models.FloatField(default=0)),
                ('high_alpha', models.FloatField(default=0)),
                ('high_gamma', models.FloatField(default=0)),
                ('high_beta', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': '脑电数据',
                'verbose_name_plural': '脑电数据',
                'db_table': 'brain_data',
            },
=======
                ('name', models.CharField(max_length=255)),
                ('signal_quality', models.IntegerField()),
                ('attention', models.IntegerField()),
                ('meditation', models.IntegerField()),
                ('delta', models.IntegerField()),
                ('theta', models.IntegerField()),
                ('low_alpha', models.IntegerField()),
                ('low_gamma', models.IntegerField()),
                ('low_beta', models.IntegerField()),
                ('high_alpha', models.IntegerField()),
                ('high_gamma', models.IntegerField()),
                ('high_beta', models.IntegerField()),
            ],
>>>>>>> c1ca8f851998afb1bf30cc888e6f7d683215f106
        ),
    ]
